# Generated by Django 2.2.1 on 2019-05-05 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('process', models.CharField(default="# model is created from the process, just set it\n# the final layer is added according with label size, using one-hot convention\nmodel.add(Conv2D(32, kernel_size = (3, 3), activation='relu',  input_shape=(256, 256, 1)))\nmodel.add(MaxPooling2D(pool_size=(2,2)))\nmodel.add(BatchNormalization())\nmodel.add(Conv2D(64, kernel_size=(3,3), activation='relu'))\nmodel.add(MaxPooling2D(pool_size=(2,2)))\nmodel.add(BatchNormalization())\nmodel.add(Conv2D(128, kernel_size=(3,3), activation='relu'))\nmodel.add(MaxPooling2D(pool_size=(2,2)))\nmodel.add(BatchNormalization())\nmodel.add(Conv2D(128, kernel_size=(3,3), activation='relu'))\nmodel.add(MaxPooling2D(pool_size=(2,2)))\nmodel.add(BatchNormalization())\nmodel.add(Conv2D(64, kernel_size=(3,3), activation='relu'))\nmodel.add(MaxPooling2D(pool_size=(2,2)))\nmodel.add(BatchNormalization())\nmodel.add(Dropout(0.2))\nmodel.add(Flatten())\nmodel.add(Dense(256, activation='relu'))\nmodel.add(Dropout(0.2))\nmodel.add(Dense(64, activation='relu'))\n", max_length=5000)),
                ('model', models.ImageField(blank=True, db_column='modelPath', max_length=300, null=True, upload_to=management.models.path_model_name)),
                ('batchSize', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('epochs', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('verbose', models.BooleanField(default=True)),
                ('progress', models.FloatField(default=0)),
                ('model_labels', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('image', models.ImageField(db_column='imagePath', max_length=300, upload_to=management.models.path_file_name)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.DataSet')),
            ],
        ),
    ]
